
server:
  port: 9191

spring:
  application:
    name: CandidateAndPosition

  datasource:
    url: jdbc:mysql://localhost:3306/candidate_positions
    username: root
    password: ac3r
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect